name: "Local Zenbo Test"
url: "http://localhost:9000/"

plugins: ['fsreader', 'blank', 'sorted', 'tags', 'markdown', 'jinja', 'fswriter', 'imagecopy']

input: "content"
template: "template"
output: "site"

# url scheme - form: layout: url
# $foo means: relpace $foo with $foo from "meta"
# %foo means: replace %foo with attribute foo from ContentObject
layouts:
  post: ["$year/$month/$day/%slug/", "_post.html"]
  page: ["%slug/", "_page.html"]
  archive: ["archive/", "_archive.html"]
  index: ["", "_index.html"]
  feed: ["feed/", "_feed.xml"]
  tags: ["tag/$title/", "_tag.html"]


options:
  fsreader: ".md"
  sorting: ['post', 'note', 'link', 'image']
  blank:
    index: ["Index", False]
    archive: ["Archive", True]
    feed: ["RSS Feed", False]
  imagecopy: "content/images/"

